-- BCCS local dev schema (Oracle Free, schema = BCCS_PRODUCT)
-- Generated to match the JPA entities exactly (no @GeneratedValue anywhere -> no sequences;
-- no @ManyToOne/@JoinColumn anywhere -> no FK constraints).
-- gvenzl/oracle-free always runs *.sql init scripts as "sqlplus -s / as sysdba" against
-- the CDB root, regardless of directory -- so we must switch container + schema ourselves.
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = BCCS_PRODUCT;

-- ===================== organization-resource-service =====================

CREATE TABLE CHANNEL_TYPE (
    CHANNEL_TYPE_ID          NUMBER(10)    NOT NULL,
    NAME                     VARCHAR2(50)  NOT NULL,
    STATUS                   VARCHAR2(1),
    OBJECT_TYPE              VARCHAR2(1),
    IS_VT_UNIT               VARCHAR2(1),
    CHECK_COMM               VARCHAR2(1),
    STOCK_TYPE               NUMBER(1),
    STOCK_REPORT_TEMPLATE    VARCHAR2(50),
    TOTAL_DEBIT              NUMBER(10),
    ALLOW_ADD_BATCH          NUMBER(1),
    SUFFIX_OBJECT_CODE       VARCHAR2(50),
    UPDATE_STAFF_OWNER_ROLE  VARCHAR2(100),
    DISCOUNT_POLICY_DEFAUT   VARCHAR2(100),
    PRICE_POLICY_DEFAUT      VARCHAR2(100),
    UPDATE_BLANK_CODE_ROLE   VARCHAR2(100),
    UPDATE_OBJECT_INFO_ROLE  VARCHAR2(100),
    UPDATE_SHOP_ROLE         VARCHAR2(100),
    CODE                     VARCHAR2(50),
    GROUP_CHANNEL_TYPE_ID    NUMBER(10),
    GROUP_CHANNEL_ID         NUMBER(10),
    IS_COLL_CHANNEL          NUMBER(2),
    IS_NOT_BLANK_CODE        NUMBER(2),
    IS_VHR_CHANNEL           NUMBER(2),
    CREATE_DATETIME          DATE,
    CREATE_USER              VARCHAR2(100),
    UPDATE_USER              VARCHAR2(50),
    UPDATE_DATETIME          DATE,
    PAYMENT_CODE             VARCHAR2(100),
    PAYMENT_TAIL             VARCHAR2(100),
    ASSIGN_CUST_STATUS       NUMBER(1),
    DESCRIPTION              VARCHAR2(1000),
    CONSTRAINT PK_CHANNEL_TYPE PRIMARY KEY (CHANNEL_TYPE_ID)
);

CREATE TABLE CUST_CHANNEL_TYPE_MAPPING (
    CUST_CHANNEL_TYPE_MAP_ID NUMBER(10)   NOT NULL,
    CUST_TYPE                VARCHAR2(10),
    CHANNEL_TYPE_ID           NUMBER(10)   NOT NULL,
    STATUS                    VARCHAR2(1)  NOT NULL,
    CREATE_USER               VARCHAR2(50),
    CREATE_DATETIME           DATE,
    UPDATE_USER               VARCHAR2(50),
    UPDATE_DATETIME           DATE,
    CONSTRAINT PK_CUST_CHANNEL_TYPE_MAPPING PRIMARY KEY (CUST_CHANNEL_TYPE_MAP_ID)
);

CREATE TABLE CUST_TYPE (
    CUST_TYPE         VARCHAR2(6)   NOT NULL,
    NAME              VARCHAR2(100) NOT NULL,
    CREATE_USER       VARCHAR2(50)  NOT NULL,
    CREATE_DATETIME   DATE          NOT NULL,
    UPDATE_USER       VARCHAR2(50),
    UPDATE_DATETIME   DATE,
    DESCRIPTION       VARCHAR2(512),
    STATUS            VARCHAR2(1)   NOT NULL,
    GROUP_TYPE        VARCHAR2(1),
    TAX               NUMBER(10),
    PLAN              VARCHAR2(1),
    REPRESENT_CUST    VARCHAR2(1),
    CUST_TYPE_ID      NUMBER(10),
    CONSTRAINT PK_CUST_TYPE PRIMARY KEY (CUST_TYPE)
);

CREATE TABLE IDENTITY_TYPE (
    ID_TYPE           VARCHAR2(10)  NOT NULL,
    NAME              VARCHAR2(100) NOT NULL,
    CREATE_USER       VARCHAR2(50)  NOT NULL,
    CREATE_DATETIME   DATE          NOT NULL,
    UPDATE_USER       VARCHAR2(50),
    UPDATE_DATETIME   DATE,
    DESCRIPTION       VARCHAR2(512),
    STATUS            VARCHAR2(1)   NOT NULL,
    MIN_LENGTH        NUMBER(3),
    MAX_LENGTH        NUMBER(3),
    VALUE_PATTERN     VARCHAR2(100),
    CONSTRAINT PK_IDENTITY_TYPE PRIMARY KEY (ID_TYPE)
);

CREATE TABLE SHOP (
    SHOP_ID                    NUMBER(10)    NOT NULL,
    NAME                       VARCHAR2(300) NOT NULL,
    PARENT_SHOP_ID             NUMBER(10),
    ACCOUNT                    VARCHAR2(40),
    BANK_NAME                  VARCHAR2(150),
    ADDRESS                    VARCHAR2(500),
    TEL                        VARCHAR2(100),
    FAX                        VARCHAR2(100),
    SHOP_CODE                  VARCHAR2(40)  NOT NULL,
    SHOP_TYPE                  VARCHAR2(1),
    CONTACT_NAME               VARCHAR2(100),
    CONTACT_TITLE              VARCHAR2(30),
    TEL_NUMBER                 VARCHAR2(30),
    EMAIL                      VARCHAR2(200),
    DESCRIPTION                VARCHAR2(100),
    PROVINCE                   VARCHAR2(50),
    PAR_SHOP_CODE               VARCHAR2(20),
    CENTER_CODE                VARCHAR2(1),
    OLD_SHOP_CODE               VARCHAR2(40),
    COMPANY                    VARCHAR2(4000),
    TIN                        VARCHAR2(50),
    SHOP                       VARCHAR2(20),
    PROVINCE_CODE              VARCHAR2(50),
    PAY_COMM                   VARCHAR2(1),
    CREATE_DATE                DATE,
    CHANNEL_TYPE_ID            NUMBER(10)    NOT NULL,
    DISCOUNT_POLICY            VARCHAR2(20),
    PRICE_POLICY               VARCHAR2(20),
    SHOP_PATH                  VARCHAR2(500),
    DISTRICT                   VARCHAR2(50),
    PRECINCT                   VARCHAR2(50),
    AREA_CODE                  VARCHAR2(200),
    ID_NO                      VARCHAR2(50),
    ID_ISSUE_PLACE             VARCHAR2(100),
    ID_ISSUE_DATE               DATE,
    STREET_BLOCK                VARCHAR2(100),
    STREET                     VARCHAR2(100),
    HOME                       VARCHAR2(100),
    ID_TYPE                    NUMBER(2),
    SHOP_PATH_NAME              VARCHAR2(2000),
    CONTRACT_NO                 VARCHAR2(100),
    FILE_ATTACH                 BLOB,
    CONTRACT_FROM_DATE          DATE,
    CONTRACT_TO_DATE            DATE,
    DEPOSIT_VALUE               NUMBER(10),
    FILE_NAME                   VARCHAR2(200),
    BUSINESS_LICENCE            VARCHAR2(200),
    BANKPLUS_MOBILE              VARCHAR2(20),
    STOCK_NUM                   NUMBER(7),
    STOCK_NUM_IMP                NUMBER(7),
    UPDATE_DATE_TIME             DATE,
    BANK_CODE                   VARCHAR2(30),
    SHOP_KEEPER_ID                NUMBER(20),
    SHOP_DIRECTOR_ID              NUMBER(20),
    FILE_ATTACHMENT_ID            NUMBER(20),
    GROUP_CHANNEL_TYPE_ID          NUMBER(10),
    STAFF_OWNER_ID                NUMBER(10),
    TENANT_ID                    NUMBER,
    FILE_CONTRACT_ID              NUMBER(20),
    FILE_CONTRACT_CATALOG_ID       NUMBER(20),
    FILE_IDENTITY_ID              NUMBER(20),
    FILE_BUSINESS_LICENSE_ID       NUMBER(20),
    BUSINESS_PROVINCE            VARCHAR2(5),
    BUSINESS_DISTRICT            VARCHAR2(5),
    BUSINESS_PRECINCT            VARCHAR2(5),
    BUSINESS_STREET_BLOCK          VARCHAR2(100),
    BUSINESS_STREET              VARCHAR2(100),
    BUSINESS_HOME                VARCHAR2(100),
    BUSINESS_AREACODE            VARCHAR2(50),
    BUSINESS_ADDRESS             VARCHAR2(500),
    CREATE_USER                 VARCHAR2(50),
    UPDATE_USER                 VARCHAR2(50),
    CREATE_DATETIME              DATE,
    STATUS                      VARCHAR2(1),
    TURNOVER                    VARCHAR2(1),
    BIRTHDAY                    DATE,
    CONSTRAINT PK_SHOP PRIMARY KEY (SHOP_ID)
);

CREATE TABLE STAFF (
    STAFF_ID                NUMBER(10)    NOT NULL,
    SHOP_ID                 NUMBER(10)    NOT NULL,
    STAFF_CODE               VARCHAR2(40)  NOT NULL,
    NAME                    VARCHAR2(300),
    BIRTHDAY                DATE,
    ID_NO                   VARCHAR2(20),
    ID_ISSUE_PLACE           VARCHAR2(150),
    ID_ISSUE_DATE            DATE,
    TEL                     VARCHAR2(15),
    TYPE                    NUMBER(10),
    SERIAL                  VARCHAR2(20),
    ISDN                    VARCHAR2(15),
    PIN                     VARCHAR2(10),
    ADDRESS                 VARCHAR2(500),
    PROVINCE                VARCHAR2(50),
    STAFF_OWN_TYPE           VARCHAR2(1),
    STAFF_OWNER_ID           NUMBER(10),
    CHANNEL_TYPE_ID          NUMBER(10),
    PRICE_POLICY             VARCHAR2(20),
    DISCOUNT_POLICY          VARCHAR2(50),
    POINT_OF_SALE            VARCHAR2(5),
    LOCK_STATUS              NUMBER(10),
    LAST_LOCK_TIME            DATE,
    IMSI                    VARCHAR2(20),
    PAYMENT_LIMIT            NUMBER(10),
    PAYMENT_USAGE            NUMBER(10),
    NOTE                    VARCHAR2(500),
    BUSINESS_METHOD          NUMBER(2),
    CONTRACT_METHOD          NUMBER(2),
    HAS_EQUIPMENT            NUMBER(2),
    HAS_TIN                 NUMBER(2),
    TIN                     VARCHAR2(50),
    DISTRICT                VARCHAR2(50),
    PRECINCT                VARCHAR2(50),
    AREA_CODE                VARCHAR2(200),
    STREET_BLOCK             VARCHAR2(100),
    STREET                  VARCHAR2(100),
    HOME                    VARCHAR2(100),
    STOCK_NUM_IMP             NUMBER(7),
    STOCK_NUM                NUMBER(7),
    POINT_OF_SALE_TYPE        NUMBER(1),
    TTNS_CODE                VARCHAR2(200),
    REGISTER_INFO            VARCHAR2(2),
    ID_TYPE                  NUMBER(2),
    LOCK_FLAG                VARCHAR2(10),
    WARNING_CONTENT           VARCHAR2(500),
    CONTRACT_NO               VARCHAR2(100),
    FILE_ATTACH               BLOB,
    CONTRACT_FROM_DATE        DATE,
    CONTRACT_TO_DATE          DATE,
    DEPOSIT_VALUE             NUMBER(10),
    BTS_CODE                 VARCHAR2(10),
    FILE_NAME                VARCHAR2(200),
    BANKPLUS_MOBILE           VARCHAR2(20),
    EMAIL                    VARCHAR2(100),
    BUSINESS_LICENCE          VARCHAR2(200),
    SUB_OWNER_TYPE            NUMBER(1),
    SUB_OWNER_ID              NUMBER(20),
    LAST_MODIFIED             DATE,
    SHOP_OWNER_ID              NUMBER(20),
    USER_ID                  NUMBER(20),
    GROUP_CHANNEL_TYPE_ID       NUMBER(10),
    BANKPLUS_BANK_CODE         VARCHAR2(50),
    GENDER                   NUMBER(2),
    TENANT_ID                 NUMBER,
    CREATE_USER               VARCHAR2(50),
    UPDATE_USER               VARCHAR2(50),
    CREATE_DATETIME            DATE,
    UPDATE_DATETIME            DATE,
    STATUS                   VARCHAR2(1),
    MAP_AREA_CHAIN_CHANNEL      VARCHAR2(50),
    CONSTRAINT PK_STAFF PRIMARY KEY (STAFF_ID)
);

CREATE TABLE STAFF_EXT (
    STAFF_EXT_ID       NUMBER(10)    NOT NULL,
    STAFF_ID           NUMBER(10),
    KEY                VARCHAR2(50),
    VALUE              VARCHAR2(4000),
    STATUS             VARCHAR2(2),
    CREATE_USER        VARCHAR2(50),
    CREATE_DATETIME    DATE,
    UPDATE_USER        VARCHAR2(50),
    UPDATE_DATETIME    DATE,
    CONSTRAINT PK_STAFF_EXT PRIMARY KEY (STAFF_EXT_ID)
);

-- ===================== product-catalog-service =====================

CREATE TABLE OPTION_SET (
    OPTION_SET_ID    NUMBER(10)    NOT NULL,
    CODE             VARCHAR2(100),
    NAME             VARCHAR2(512),
    STATUS           VARCHAR2(1),
    CREATE_USER      VARCHAR2(50),
    CREATE_DATETIME  DATE,
    UPDATE_USER      VARCHAR2(50),
    UPDATE_DATETIME  DATE,
    DESCRIPTION      VARCHAR2(512),
    CONSTRAINT PK_OPTION_SET PRIMARY KEY (OPTION_SET_ID)
);

CREATE TABLE OPTION_SET_VALUE (
    OPTION_SET_VALUE_ID   NUMBER(10)    NOT NULL,
    OPTION_SET_ID         NUMBER(10),
    NAME                  VARCHAR2(512),
    VALUE                 VARCHAR2(1000),
    STATUS                VARCHAR2(1),
    DESCRIPTION           VARCHAR2(512),
    CREATE_USER           VARCHAR2(50),
    CREATE_DATETIME       DATE,
    UPDATE_USER           VARCHAR2(50),
    UPDATE_DATETIME       DATE,
    PARENT_ID             NUMBER(10),
    CONSTRAINT PK_OPTION_SET_VALUE PRIMARY KEY (OPTION_SET_VALUE_ID)
);

CREATE TABLE PRODUCT_OFFERING (
    PRODUCT_OFFERING_ID           NUMBER(10)    NOT NULL,
    PRODUCT_SPEC_ID               NUMBER(10),
    PRODUCT_OFFER_TYPE_ID          NUMBER(10),
    NAME                          VARCHAR2(500),
    CODE                          VARCHAR2(50),
    SUB_TYPE                      VARCHAR2(1),
    TELECOM_SERVICE_ID             NUMBER(10),
    DESCRIPTION                   VARCHAR2(4000),
    STATUS                        VARCHAR2(1),
    EFFECT_DATETIME                DATE,
    EXPIRE_DATETIME                DATE,
    CREATE_USER                   VARCHAR2(50),
    CREATE_DATETIME                DATE,
    UPDATE_USER                   VARCHAR2(50),
    UPDATE_DATETIME                DATE,
    VERSION                       VARCHAR2(50),
    CHECK_SERIAL                   NUMBER(1),
    CHECK_DEPOSIT                  NUMBER(1),
    UNIT                          VARCHAR2(10),
    ACCOUNTING_MODEL_CODE           VARCHAR2(50),
    ACCOUNTING_MODEL_NAME           VARCHAR2(100),
    ACCOUNTING_NAME                VARCHAR2(100),
    ACCOUNTING_CODE                VARCHAR2(50),
    DEMO_DURATION                  NUMBER(10),
    IS_DEMO                       NUMBER(1),
    DEVICE_TYPE                   VARCHAR2(20),
    TRANSCEIVER                   NUMBER(1),
    STOCK_MODEL_TYPE                NUMBER(1),
    OWNER_SHOP_ID                  NUMBER(10),
    RETURN_STOCK_WHEN_CANCELLED       VARCHAR2(2),
    RETURN_STOCK_WHEN_CANCELLED1      VARCHAR2(2),
    SAP_MATERIAL_NUMBER              NUMBER(9),
    USAGE_ID                      VARCHAR2(100),
    DISTRIBUTE                    VARCHAR2(1),
    NUM_MONTH                     NUMBER(10),
    IS_BUNDLE                     VARCHAR2(10),
    SAP_PRODUCT_TYPE                VARCHAR2(1),
    CONSTRAINT PK_PRODUCT_OFFERING PRIMARY KEY (PRODUCT_OFFERING_ID)
);

CREATE TABLE PRODUCT_PACKAGE (
    PRODUCT_PACKAGE_ID     NUMBER(10)    NOT NULL,
    NAME                   VARCHAR2(500),
    CODE                   VARCHAR2(50),
    DESCRIPTION            VARCHAR2(4000),
    STATUS                 VARCHAR2(1),
    EFFECT_DATETIME         DATE,
    EXPIRE_DATETIME         DATE,
    CREATE_USER            VARCHAR2(50),
    CREATE_DATETIME         DATE,
    UPDATE_USER            VARCHAR2(50),
    UPDATE_DATETIME         DATE,
    VERSION                VARCHAR2(50),
    TYPE                   VARCHAR2(1),
    ACCOUNTING_ID           NUMBER(10),
    FEE_TYPE                VARCHAR2(1),
    TELECOM_SERVICE_ID       NUMBER(10),
    SALE_TYPE               VARCHAR2(1),
    UNIT                   VARCHAR2(10),
    NOTE1                  VARCHAR2(1000),
    NOTE2                  VARCHAR2(1000),
    NOTE                   VARCHAR2(1000),
    AREA_GROUP_ID           NUMBER(10),
    OWNER_SHOP_ID           NUMBER(10),
    SAP_MATERIAL_NUMBER      NUMBER(10),
    IT_TELCOL               VARCHAR2(6),
    CONSTRAINT PK_PRODUCT_PACKAGE PRIMARY KEY (PRODUCT_PACKAGE_ID)
);

CREATE TABLE PRODUCT_PACKAGE_FEE (
    PRODUCT_PACKAGE_FEE_ID   NUMBER(10)    NOT NULL,
    PRODUCT_PACKAGE_ID       NUMBER(10),
    PRICE_POLICY_ID          NUMBER(10),
    PRICE_TYPE_ID            NUMBER(10),
    NAME                    VARCHAR2(50),
    DESCRIPTION              VARCHAR2(4000),
    PRICE                   NUMBER(10),
    VAT                     NUMBER(10),
    EFFECT_DATETIME          DATE,
    EXPIRE_DATETIME          DATE,
    PRIORITY                NUMBER(2),
    EFFECT_TYPE              VARCHAR2(1),
    CRON_EXPRESSION           VARCHAR2(50),
    REAL_STEP                VARCHAR2(50),
    REVENUE_OBJ              VARCHAR2(50),
    CREATE_USER              VARCHAR2(50),
    CREATE_DATETIME           DATE,
    UPDATE_USER              VARCHAR2(50),
    UPDATE_DATETIME           DATE,
    STATUS                  VARCHAR2(1),
    CODE                    VARCHAR2(50),
    FILE_ATTACHMENT_ID        NUMBER(10),
    DISTRIBUTE               NUMBER(2),
    SAP_MATERIAL_NUMBER        NUMBER(10),
    CONSTRAINT PK_PRODUCT_PACKAGE_FEE PRIMARY KEY (PRODUCT_PACKAGE_FEE_ID)
);

CREATE TABLE PRODUCT_SPEC_CHAR (
    PRODUCT_SPEC_CHAR_ID       NUMBER(10)    NOT NULL,
    NAME                      VARCHAR2(500),
    DESCRIPTION                VARCHAR2(512),
    VALUE_TYPE                 VARCHAR2(2),
    CHAR_TYPE                  VARCHAR2(2),
    MIN_CARDINALITY             NUMBER(10),
    MAX_CARDINALITY             NUMBER(10),
    STATUS                     VARCHAR2(1),
    CREATE_USER                 VARCHAR2(50),
    CREATE_DATETIME              DATE,
    UPDATE_USER                 VARCHAR2(50),
    UPDATE_DATETIME              DATE,
    CODE                       VARCHAR2(200),
    PRODUCT_SPEC_CHAR_TYPE_ID      VARCHAR2(100),
    VALUE_SET_TYPE               NUMBER(1),
    RESPONSE_CLASS               VARCHAR2(50),
    SQL_QUERY                   VARCHAR2(500),
    DISPLAY_OBJECT               VARCHAR2(50),
    VALUE_OBJECT                 VARCHAR2(50),
    SOLR_QUERY                  VARCHAR2(500),
    SOLR_CORE                   VARCHAR2(50),
    SOLR_SCHEMA                 VARCHAR2(50),
    DATA_TYPE                   VARCHAR2(40),
    WS_WSDL                     VARCHAR2(4000),
    TEMPLATE_REQUEST              CLOB,
    VALIDATE_PATTERN              VARCHAR2(1000),
    EXT_DATA                    VARCHAR2(1000),
    NOTE                       VARCHAR2(256),
    CONSTRAINT PK_PRODUCT_SPEC_CHAR PRIMARY KEY (PRODUCT_SPEC_CHAR_ID)
);

CREATE TABLE PRODUCT_SPEC_CHAR_VALUE (
    PRODUCT_SPEC_CHAR_VALUE_ID   NUMBER(10)    NOT NULL,
    PRODUCT_SPEC_CHAR_ID         NUMBER(10),
    VALUE_TYPE                  VARCHAR2(10),
    IS_DEFAULT                  NUMBER(1)     NOT NULL,
    VALUE                      VARCHAR2(4000),
    UNIT_OF_MEASURE              VARCHAR2(10),
    VALUE_FROM                  VARCHAR2(4000),
    VALUE_TO                    VARCHAR2(4000),
    RANGE_INTERVAL               VARCHAR2(10),
    STATUS                     VARCHAR2(1),
    CREATE_USER                 VARCHAR2(50),
    CREATE_DATETIME              DATE,
    UPDATE_USER                 VARCHAR2(50),
    UPDATE_DATETIME              DATE,
    NAME                       VARCHAR2(500),
    SPECIFIC_VALUE               CLOB,
    NOTE                       VARCHAR2(256),
    CONSTRAINT PK_PRODUCT_SPEC_CHAR_VALUE PRIMARY KEY (PRODUCT_SPEC_CHAR_VALUE_ID)
);

CREATE TABLE PROD_PACK_SHOP (
    PROD_PACK_SHOP_ID   NUMBER(10)    NOT NULL,
    SHOP_ID             NUMBER(10),
    PROD_PACK_TYPE_ID   NUMBER(10),
    STATUS             VARCHAR2(1),
    CREATE_USER         VARCHAR2(50),
    CREATE_DATETIME      DATE,
    UPDATE_USER         VARCHAR2(50),
    UPDATE_DATETIME      DATE,
    CONSTRAINT PK_PROD_PACK_SHOP PRIMARY KEY (PROD_PACK_SHOP_ID)
);

CREATE TABLE PRODUCT_OFFER_TYPE (
    PRODUCT_OFFER_TYPE_ID   NUMBER(10)     NOT NULL,
    PARENT_ID               NUMBER(10),
    NAME                    VARCHAR2(50)   NOT NULL,
    DESCRIPTION              VARCHAR2(2000),
    STATUS                  VARCHAR2(1),
    CREATE_USER              VARCHAR2(50),
    CREATE_DATETIME           DATE,
    UPDATE_USER              VARCHAR2(50),
    UPDATE_DATETIME           DATE,
    CONSTRAINT PK_PRODUCT_OFFER_TYPE PRIMARY KEY (PRODUCT_OFFER_TYPE_ID)
);

CREATE TABLE PRODUCT_OFFER_PRICE (
    PRODUCT_OFFER_PRICE_ID   NUMBER(10)    NOT NULL,
    PRODUCT_OFFERING_ID      NUMBER(10),
    PRICE_POLICY_ID          NUMBER(10),
    PRICE_TYPE_ID            NUMBER(10),
    NAME                    VARCHAR2(50),
    DESCRIPTION              VARCHAR2(4000),
    PRICE                   NUMBER(20),
    VAT                     NUMBER(10),
    PLEDGE_AMOUNT            NUMBER(20),
    PLEDGE_TIME              NUMBER(10),
    PRIOR_PAY                VARCHAR2(10),
    STATUS                  VARCHAR2(1),
    EFFECT_DATETIME          DATE,
    EXPIRE_DATETIME          DATE,
    PRIORITY                NUMBER(2),
    EFFECT_TYPE              VARCHAR2(1),
    CRON_EXPRESSION           VARCHAR2(50),
    CREATE_USER              VARCHAR2(50),
    CREATE_DATETIME           DATE,
    UPDATE_USER              VARCHAR2(50),
    UPDATE_DATETIME           DATE,
    PROGRAM_CODE             VARCHAR2(50),
    PROGRAM_MONTH             NUMBER(10),
    IS_SELECT_ALL_SHOP        VARCHAR2(1),
    LIMITED                 NUMBER(1),
    CONSTRAINT PK_PRODUCT_OFFER_PRICE PRIMARY KEY (PRODUCT_OFFER_PRICE_ID)
);

CREATE TABLE PRODUCT_OFFER_RELATION (
    PRODUCT_OFFER_RELATION_ID   NUMBER(10)    NOT NULL,
    RELATION_TYPE_ID            NUMBER(10),
    MAIN_OFFER_ID                NUMBER(10),
    RELATION_OFFER_ID            NUMBER(10),
    STATUS                      VARCHAR2(1),
    CREATE_USER                  VARCHAR2(50),
    CREATE_DATETIME               DATE,
    UPDATE_USER                  VARCHAR2(50),
    UPDATE_DATETIME               DATE,
    CONFIG_PHASE                 VARCHAR2(200),
    DESCRIPTION                  VARCHAR2(512),
    EFFECT_DATETIME               DATE,
    EXPIRE_DATETIME               DATE,
    CONSTRAINT PK_PRODUCT_OFFER_RELATION PRIMARY KEY (PRODUCT_OFFER_RELATION_ID)
);

CREATE TABLE PRODUCT_OFFER_RELATION_DETAIL (
    PRODUCT_OFFER_RELATION_DETAIL   NUMBER(38)    NOT NULL,
    PRODUCT_OFFER_RELATION_ID        NUMBER(10),
    PRODUCT_SPEC_CHAR_ID             NUMBER(10),
    PRODUCT_SPEC_CHAR_VALUE_ID        NUMBER(10),
    STATUS                          VARCHAR2(1),
    CREATE_USER                      VARCHAR2(50),
    CREATE_DATETIME                   DATE,
    UPDATE_USER                      VARCHAR2(50),
    UPDATE_DATETIME                   DATE,
    SPECIFIC_VALUE                    VARCHAR2(50),
    DESCRIPTION                      VARCHAR2(512),
    EFFECT_DATETIME                   DATE,
    EXPIRE_DATETIME                   DATE,
    CONSTRAINT PK_PRODUCT_OFFER_RELATION_DETAIL PRIMARY KEY (PRODUCT_OFFER_RELATION_DETAIL)
);

CREATE TABLE PRODUCT_OFFER_CHAR_USE (
    PRODUCT_OFFER_CHAR_USE_ID   NUMBER(10)    NOT NULL,
    ORDER_CHAR                  NUMBER(10),
    TYPE                       VARCHAR2(1),
    PRODUCT_OFFERING_ID         NUMBER(10),
    PRODUCT_SPEC_CHAR_VALUE_ID   NUMBER(10),
    PRODUCT_SPEC_CHAR_ID         NUMBER(10),
    CREATE_USER                 VARCHAR2(50),
    CREATE_DATETIME              DATE,
    UPDATE_USER                 VARCHAR2(50),
    UPDATE_DATETIME              DATE,
    STATUS                     VARCHAR2(1),
    SPECIFIC_VALUE               VARCHAR2(500),
    EFFECT_DATETIME              DATE,
    EXPIRE_DATETIME              DATE,
    LIMITED                     NUMBER(1),
    DESCRIPTION                 VARCHAR2(1000),
    CONSTRAINT PK_PRODUCT_OFFER_CHAR_USE PRIMARY KEY (PRODUCT_OFFER_CHAR_USE_ID)
);

CREATE TABLE PRODUCT_PACKAGE_CHAR_USE (
    PRODUCT_PACKAGE_CHAR_USE_ID   NUMBER(10)    NOT NULL,
    PRODUCT_PACKAGE_ID            NUMBER(10),
    PRODUCT_SPEC_CHAR_ID           NUMBER(10),
    PRODUCT_SPEC_CHAR_VALUE_ID      NUMBER(10),
    STATUS                        VARCHAR2(1),
    CREATE_USER                    VARCHAR2(50),
    CREATE_DATETIME                 DATE,
    UPDATE_USER                    VARCHAR2(50),
    UPDATE_DATETIME                 DATE,
    SPECIFIC_VALUE                  VARCHAR2(50),
    LIMITED                        NUMBER(1),
    EFFECT_DATETIME                 DATE,
    EXPIRE_DATETIME                 DATE,
    DESCRIPTION                    VARCHAR2(100),
    CONSTRAINT PK_PRODUCT_PACKAGE_CHAR_USE PRIMARY KEY (PRODUCT_PACKAGE_CHAR_USE_ID)
);

CREATE TABLE PROD_PACK_PRODUCT_OFFER_TYPE (
    PROD_PACK_TYPE_ID       NUMBER(10)    NOT NULL,
    PRODUCT_PACKAGE_ID      NUMBER(10),
    PRODUCT_OFFER_TYPE_ID   NUMBER(10),
    STATUS                 VARCHAR2(1),
    UPDATE_STOCK            VARCHAR2(1),
    CHECK_STAFF_STOCK        VARCHAR2(1),
    CHECK_SHOP_STOCK         VARCHAR2(1),
    CREATE_USER             VARCHAR2(50),
    CREATE_DATETIME          DATE,
    UPDATE_USER             VARCHAR2(50),
    UPDATE_DATETIME          DATE,
    REQUIRE                VARCHAR2(1),
    DESCRIPTION             VARCHAR2(200),
    LIMIT_GOODS             NUMBER(10),
    DISTRIBUTE              NUMBER(2),
    TRANSFER_IM             VARCHAR2(1),
    CONSTRAINT PK_PROD_PACK_PRODUCT_OFFER_TYPE PRIMARY KEY (PROD_PACK_TYPE_ID)
);

CREATE TABLE PACKAGE_OFFER (
    PROD_PACK_OFFER_ID          NUMBER(10)    NOT NULL,
    PROD_PACK_TYPE_ID           NUMBER(10),
    PRODUCT_OFFERING_ID         NUMBER(10),
    PRODUCT_OFFER_TYPE_ID        NUMBER(10),
    PRODUCT_PACKAGE_ID           NUMBER(10),
    PRODUCT_OFFER_PRICE_ID        NUMBER(10),
    OFFER_CODE                  VARCHAR2(100),
    OFFER_NAME                  VARCHAR2(500),
    OFFER_TYPE                  VARCHAR2(50),
    STATUS                      VARCHAR2(1),
    PACKAGE_CODE                 VARCHAR2(100),
    PACKAGE_NAME                 VARCHAR2(500),
    PRICE                       NUMBER(12),
    VAT                         NUMBER(2),
    NUM_OFFER                   NUMBER(5),
    ORIGINAL_PRICE               NUMBER(12),
    MIN_PRICE                   NUMBER(12),
    MAX_PRICE                   NUMBER(12),
    PRICE_TYPE                  VARCHAR2(2),
    SUPPLY_METHOD                VARCHAR2(50),
    PROVIDE_METHOD_ID             NUMBER(2),
    SAP_MATERIAL_NUMBER           NUMBER(10),
    SAP_MATERIAL_NAME             VARCHAR2(200),
    ACCOUNTING_MODEL_CODE         VARCHAR2(100),
    ACCOUNTING_MODEL_NAME         VARCHAR2(200),
    CREATE_DATETIME               DATE,
    EFFECT_DATETIME               DATE,
    EXPIRE_DATETIME               DATE,
    UPDATE_DATETIME               DATE,
    CREATE_USER                  VARCHAR2(50),
    UPDATE_USER                  VARCHAR2(50),
    IS_MANDATORY                 VARCHAR2(1),
    CHECK_STAFF_STOCK              VARCHAR2(1),
    CHECK_SHOP_STOCK               VARCHAR2(1),
    SHOP_VALUE                   VARCHAR2(500),
    UPDATE_STOCK_ID                NUMBER(10),
    UPDATE_STOCK_VALUE             VARCHAR2(500),
    REASON_EFFECT_DATE             DATE,
    REASON_EXPIRE_DATE             DATE,
    NEW_OR_SOLD                  VARCHAR2(1),
    ACTION                      VARCHAR2(2),
    PRODUCT_TYPE_NAME              VARCHAR2(200),
    ERROR_CODE                   VARCHAR2(20),
    KEY_MES                     VARCHAR2(200),
    FAKE_PROD_PACK_TYPE_ID          VARCHAR2(200),
    PLEDGE_TIME                  VARCHAR2(50),
    PLEDGE_AMOUNT                 VARCHAR2(50),
    LST_SHOP_CODE                 VARCHAR2(500),
    LIMIT_GOODS                  NUMBER(10),
    PROD_PACK_TYPE_LIMIT_GOODS       NUMBER(10),
    CONCAT_SALE_PROGRAM            VARCHAR2(500),
    CHECK_SERIAL                 NUMBER(1),
    DESCRIPTION                  VARCHAR2(2000),
    DESCRIPTION_OFFER              VARCHAR2(2000),
    REASON_CODE                  VARCHAR2(20),
    REASON_NAME                  VARCHAR2(200),
    SHOW_OR_HIDE                 VARCHAR2(1),
    DISTRIBUTE                   NUMBER(1),
    DISTRIBUTE_NAME                VARCHAR2(200),
    TYPE_ALLOCATION                VARCHAR2(2),
    NUM_MONTH_ALLOCATION            VARCHAR2(20),
    CONSTRAINT PK_PACKAGE_OFFER PRIMARY KEY (PROD_PACK_OFFER_ID)
);

-- ===================== product-policy-service =====================

CREATE TABLE ACTION (
    ACTION_CODE       VARCHAR2(10)  NOT NULL,
    NAME              VARCHAR2(512),
    DESCRIPTION       VARCHAR2(512),
    STATUS            VARCHAR2(1),
    CREATE_USER       VARCHAR2(50),
    CREATE_DATETIME   DATE,
    UPADTE_USER       VARCHAR2(50),
    UPDATE_DATETIME   DATE,
    TYPE              VARCHAR2(2),
    REASON_TYPE       VARCHAR2(20),
    CONSTRAINT PK_ACTION PRIMARY KEY (ACTION_CODE)
);

CREATE TABLE DISCOUNT_PROMOTION (
    DISCOUNT_PROMOTION_ID   NUMBER(10)     NOT NULL,
    TELECOM_SERVICE_ID       VARCHAR2(100)  NOT NULL,
    CODE                    VARCHAR2(20),
    NAME                    VARCHAR2(1500),
    TYPE                    VARCHAR2(1),
    SYSTEM_TYPE              VARCHAR2(1),
    DISCOUNT_METHOD          VARCHAR2(1),
    DISCOUNT_POLICY          VARCHAR2(10),
    SUB_TYPE                 VARCHAR2(1),
    MONTH_COMMITMENT          NUMBER(10),
    PRICE_PLAN               VARCHAR2(30),
    MONTH_AMOUNT              NUMBER(10),
    STATUS                   VARCHAR2(1),
    DESCRIPTION               VARCHAR2(4000),
    CONTENT                  VARCHAR2(4000),
    AREA_CODE                 VARCHAR2(300),
    EFFECT_DATETIME            TIMESTAMP      NOT NULL,
    EXPIRE_DATETIME            TIMESTAMP,
    CREATE_USER                VARCHAR2(50),
    CREATE_DATETIME             TIMESTAMP,
    UPDATE_USER                VARCHAR2(50),
    UPDATE_DATETIME             TIMESTAMP,
    CYCLE                     NUMBER(10),
    LIST_TYPE                  VARCHAR2(50),
    SUB_LIST_ID                 NUMBER(7),
    NOTE                      VARCHAR2(4000),
    CONSTRAINT PK_DISCOUNT_PROMOTION PRIMARY KEY (DISCOUNT_PROMOTION_ID)
);

CREATE TABLE DISCOUNT_PROMOTION_CHAR_USE (
    DISCOUNT_PROMOTION_CHAR_USE_ID   NUMBER(10)    NOT NULL,
    DISCOUNT_PROMOTION_ID            NUMBER(10),
    PRODUCT_SPEC_CHAR_VALUE_ID         NUMBER(10),
    PRODUCT_SPEC_CHAR_ID               NUMBER(10),
    CREATE_USER                       VARCHAR2(50),
    CREATE_DATETIME                    TIMESTAMP,
    UPDATE_USER                       VARCHAR2(50),
    UPDATE_DATETIME                    TIMESTAMP,
    STATUS                            VARCHAR2(1),
    SPECIFIC_VALUE                     VARCHAR2(2000),
    EFFECT_DATETIME                    TIMESTAMP,
    EXPIRE_DATETIME                    TIMESTAMP,
    LIMITED                           NUMBER(1),
    NOTE                              VARCHAR2(2000),
    CONSTRAINT PK_DISCOUNT_PROMOTION_CHAR_USE PRIMARY KEY (DISCOUNT_PROMOTION_CHAR_USE_ID)
);

CREATE TABLE MAP_ACTIVE_INFO (
    ID                   NUMBER(18)    NOT NULL,
    TEL_SERVICE_ID        NUMBER(10)    NOT NULL,
    PRODUCT_CODE          VARCHAR2(50),
    PRODUCT_NAME          VARCHAR2(100),
    REG_REASON_ID         NUMBER(10)    NOT NULL,
    REASON_NAME           VARCHAR2(100),
    PROM_CODE             VARCHAR2(50),
    PROM_NAME             VARCHAR2(150),
    CHANNEL_TYPE_ID        NUMBER(10)    NOT NULL,
    CHANNEL_NAME           VARCHAR2(50),
    PROVINCE_CODE          VARCHAR2(50)  NOT NULL,
    DISTRICT_CODE          VARCHAR2(50),
    EFFECT_DATE            DATE,
    END_DATE              DATE,
    PROVINCE_NAME          VARCHAR2(50),
    DISTRICT_NAME          VARCHAR2(50),
    OFFER_ID               NUMBER(10),
    OFFER_NAME             VARCHAR2(100),
    STATUS                NUMBER(2),
    PRECINCT_NAME          VARCHAR2(50),
    PRECINCT_CODE          VARCHAR2(50),
    SHOP_CODE              VARCHAR2(50),
    STAFF_CODE             VARCHAR2(50),
    ACTION_CODE            VARCHAR2(10),
    ACTION_NAME            VARCHAR2(50),
    LIMIT_NUMBER           VARCHAR2(10),
    CAPTCHAR_REQUIRE        NUMBER(1),
    UNIT                  VARCHAR2(2),
    CUSTOMER_GROUP          VARCHAR2(10),
    CUSTOMER_TYPE           VARCHAR2(10),
    SUB_TYPE               VARCHAR2(4),
    SUB_GROUP              VARCHAR2(10),
    POLICY_DOC              VARCHAR2(100),
    ACTION_GROUP            VARCHAR2(50),
    ACTION_GROUP_NAME        VARCHAR2(200),
    FILE_NAME              VARCHAR2(200),
    STATION_ID              NUMBER(10),
    SHOP_ID                NUMBER(10),
    FILE_ATTACH             BLOB,
    CREATE_USER             VARCHAR2(50),
    ISSUE_DATETIME           DATE,
    STATION_CODES            VARCHAR2(1000),
    PAY_TYPE                VARCHAR2(1),
    TECHNOLOGY              VARCHAR2(10),
    UPDATE_DATETIME          DATE,
    UPDATE_USER             VARCHAR2(50),
    AREA_GROUP_CODE          VARCHAR2(50),
    VAS_CODE                VARCHAR2(50),
    VAS_NAME                VARCHAR2(100),
    NODE_CODE               VARCHAR2(1500),
    NOTE                   VARCHAR2(3000),
    GROUP_NODE_CODE          VARCHAR2(50),
    STAFF_TYPE              VARCHAR2(5),
    BUSINESS_NO             VARCHAR2(4000),
    SUB_GROUP_CODE           VARCHAR2(4000),
    SME_CUSTOMER_GROUP        VARCHAR2(4000),
    IMPORT_OFFLINE_ID         NUMBER(10),
    CONSTRAINT PK_MAP_ACTIVE_INFO PRIMARY KEY (ID)
);

CREATE TABLE MAP_ACTIVE_INFO_TGDD (
    ID                   NUMBER(18)    NOT NULL,
    TEL_SERVICE_ID        NUMBER(10),
    PRODUCT_CODE          VARCHAR2(30),
    PRODUCT_NAME          VARCHAR2(100),
    REG_REASON_ID         NUMBER(10),
    REASON_NAME           VARCHAR2(100),
    PROM_CODE             VARCHAR2(10),
    PROM_NAME             VARCHAR2(150),
    CHANNEL_TYPE_ID        NUMBER(10),
    CHANNEL_NAME           VARCHAR2(50),
    PROVINCE_CODE          VARCHAR2(50),
    DISTRICT_CODE          VARCHAR2(50),
    EFFECT_DATE            DATE,
    END_DATE              DATE,
    PROVINCE_NAME          VARCHAR2(50),
    DISTRICT_NAME          VARCHAR2(50),
    OFFER_ID               NUMBER(10),
    OFFER_NAME             VARCHAR2(100),
    STATUS                NUMBER(2),
    PRECINCT_NAME          VARCHAR2(50),
    PRECINCT_CODE          VARCHAR2(50),
    SHOP_CODE              VARCHAR2(20),
    STAFF_CODE             VARCHAR2(50),
    ACTION_CODE            VARCHAR2(10),
    ACTION_NAME            VARCHAR2(100),
    LIMIT_NUMBER           VARCHAR2(10),
    CAPTCHAR_REQUIRE        NUMBER(1),
    UNIT                  VARCHAR2(2),
    CUSTOMER_GROUP          VARCHAR2(10),
    CUSTOMER_TYPE           VARCHAR2(10),
    SUB_TYPE               VARCHAR2(4),
    SUB_GROUP              VARCHAR2(10),
    POLICY_DOC              VARCHAR2(100),
    ACTION_GROUP            VARCHAR2(50),
    ACTION_GROUP_NAME        VARCHAR2(200),
    FILE_NAME              VARCHAR2(200),
    STATION_ID              NUMBER(10),
    SHOP_ID                NUMBER(10),
    FILE_ATTACH             BLOB,
    CREATE_USER             VARCHAR2(50),
    ISSUE_DATETIME           DATE,
    STATION_CODES            VARCHAR2(1000),
    PAY_TYPE                VARCHAR2(1),
    TECHNOLOGY              VARCHAR2(10),
    UPDATE_DATETIME          DATE,
    UPDATE_USER             VARCHAR2(50),
    AREA_GROUP_CODE          VARCHAR2(50),
    VAS_CODE                VARCHAR2(50),
    VAS_NAME                VARCHAR2(100),
    NODE_CODE               VARCHAR2(1500),
    NOTE                   VARCHAR2(3000),
    GROUP_NODE_CODE          VARCHAR2(50),
    CONNECT_METHOD           NUMBER(1),
    ATTACH_TEL_SERVICE_ID      NUMBER(10),
    ATTACH_PRODUCT_CODE       VARCHAR2(100),
    SINGLE_OR_COMBO          NUMBER(1),
    OLD_PRODUCT_CODE         VARCHAR2(30),
    ATTACH_PROM_CODE         VARCHAR2(30),
    ATTACH_REASON_ID         NUMBER(10),
    SUB_GROUP_CODE           VARCHAR2(4000),
    PROJECT_CODE            VARCHAR2(4000),
    IMPORT_OFFLINE_ID         NUMBER(10),
    CONSTRAINT PK_MAP_ACTIVE_INFO_TGDD PRIMARY KEY (ID)
);

CREATE TABLE MAPPING (
    ID                   NUMBER(18)    NOT NULL,
    VAS                  VARCHAR2(10),
    VAS_NAME              VARCHAR2(100),
    PRODUCT_NAME          VARCHAR2(100),
    PRODUCT_CODE          VARCHAR2(15),
    ACTION_NAME           VARCHAR2(100),
    ACTION_CODE           VARCHAR2(30),
    REASON_ID             NUMBER(10),
    REASON_NAME           VARCHAR2(100),
    TEL_SERVICE_ID         NUMBER(10),
    SALE_SERVICE_ID        NUMBER(10),
    SALE_SERVICE_NAME       VARCHAR2(100),
    SALE_SERVICE_CODE       VARCHAR2(20),
    CHANNEL               VARCHAR2(1),
    STATUS                VARCHAR2(1)   NOT NULL,
    USER_CREATE            VARCHAR2(30),
    USER_UPDATE            VARCHAR2(30),
    CREATE_DATETIME         DATE,
    CHANGE_DATETIME         DATE,
    IP                    VARCHAR2(50),
    END_EFFECT_DATE         DATE,
    TYPE_MAPPING           VARCHAR2(1),
    ACTION_ID              VARCHAR2(30),
    CONSTRAINT PK_MAPPING PRIMARY KEY (ID)
);

CREATE TABLE REASON (
    REASON_ID           NUMBER(10)    NOT NULL,
    REASON_CODE          VARCHAR2(20),
    REASON_TYPE          VARCHAR2(20),
    NAME                VARCHAR2(512),
    PAY_TYPE             VARCHAR2(1),
    TEL_SERVICE          VARCHAR2(1000),
    DESCRIPTION          VARCHAR2(512),
    STATUS              VARCHAR2(1),
    CREATE_USER          VARCHAR2(50),
    CREATE_DATETIME       TIMESTAMP,
    UPDATE_USER          VARCHAR2(50),
    UPDATE_DATETIME       TIMESTAMP,
    LIMIT_NUMBER_ISDN      NUMBER(10),
    LIMIT_NUMBER_USER      NUMBER(10),
    TYPE                VARCHAR2(1),
    EFFECT_DATETIME       TIMESTAMP,
    EXPIRE_DATETIME       TIMESTAMP,
    PRIORITY             NUMBER(10),
    NOTE                VARCHAR2(1000),
    CONSTRAINT PK_REASON PRIMARY KEY (REASON_ID)
);

CREATE TABLE REF_PROD_PACK_PO_TYPE (
    PROD_PACK_TYPE_ID      NUMBER(10)   NOT NULL,
    PRODUCT_PACKAGE_ID      NUMBER(10)   NOT NULL,
    PRODUCT_OFFER_TYPE_ID    NUMBER(10)   NOT NULL,
    STATUS                 VARCHAR2(1),
    UPDATE_STOCK            VARCHAR2(1),
    CHECK_STAFF_STOCK        VARCHAR2(1),
    CHECK_SHOP_STOCK         VARCHAR2(1),
    UPDATE_DATETIME          DATE,
    LIMIT_GOODS             NUMBER(10),
    TRANSFER_IM             VARCHAR2(1),
    CONSTRAINT PK_REF_PROD_PACK_PO_TYPE PRIMARY KEY (PROD_PACK_TYPE_ID)
);

CREATE TABLE REF_PRODUCT_PACKAGE (
    PRODUCT_PACKAGE_ID    NUMBER(10)    NOT NULL,
    NAME                  VARCHAR2(500) NOT NULL,
    CODE                  VARCHAR2(50),
    DESCRIPTION            VARCHAR2(512),
    STATUS                VARCHAR2(1),
    EFFECT_DATETIME         DATE,
    EXPIRE_DATETIME         DATE,
    UPDATE_DATETIME         DATE,
    TYPE                  VARCHAR2(1),
    ACCOUNTING_ID          NUMBER(10),
    FEE_TYPE               VARCHAR2(1),
    TELECOM_SERVICE_ID      NUMBER(10),
    CONSTRAINT PK_REF_PRODUCT_PACKAGE PRIMARY KEY (PRODUCT_PACKAGE_ID)
);

CREATE TABLE REF_PRODUCT_PACKAGE_FEE (
    PRODUCT_PACKAGE_FEE_ID   NUMBER(10)   NOT NULL,
    PRODUCT_PACKAGE_ID       NUMBER(10)   NOT NULL,
    PRICE_POLICY_ID          NUMBER(10)   NOT NULL,
    PRICE_TYPE_ID            NUMBER(10)   NOT NULL,
    NAME                    VARCHAR2(50),
    PRICE                   NUMBER(10),
    VAT                    NUMBER(10),
    EFFECT_DATETIME           DATE,
    EXPIRE_DATETIME           DATE,
    STATUS                  VARCHAR2(1),
    CONSTRAINT PK_REF_PRODUCT_PACKAGE_FEE PRIMARY KEY (PRODUCT_PACKAGE_FEE_ID)
);

-- ===================== product-area-service =====================

CREATE TABLE AREA (
    AREA_CODE          VARCHAR2(200) NOT NULL,
    PARENT_CODE         VARCHAR2(200),
    AREA_GROUP          VARCHAR2(5),
    PROVINCE            VARCHAR2(50),
    DISTRICT            VARCHAR2(50),
    PRECINCT            VARCHAR2(50),
    STREET_BLOCK         VARCHAR2(50),
    NAME               VARCHAR2(100),
    FULL_NAME           VARCHAR2(400),
    CENTER             VARCHAR2(1),
    PSTN_CODE           VARCHAR2(20),
    PROVINCE_CODE        VARCHAR2(50),
    STATUS             VARCHAR2(1),
    CREATE_USER         VARCHAR2(50),
    UPDATE_USER         VARCHAR2(50),
    CREATE_DATETIME      TIMESTAMP,
    UPDATE_DATETIME      TIMESTAMP,
    REGION_ID           NUMBER(20),
    VT_MAP_CODE          VARCHAR2(20),
    SQUARE             NUMBER(20),
    POPULATION          NUMBER(20),
    HOUSEHOLDS          NUMBER(20),
    AREA_TYPE           VARCHAR2(10),
    VN_CODE             VARCHAR2(50),
    VN_NAME             VARCHAR2(100),
    IS_NEW             VARCHAR2(1),
    CONSTRAINT PK_AREA PRIMARY KEY (AREA_CODE)
);
