-- Sample data for BCCS local dev DB. No FK constraints exist (matches the JPA entities,
-- which have no @ManyToOne/@JoinColumn), so insert order is not functionally required,
-- but kept in a logical lookup-first order for readability.
-- Each *.sql init script gets its own fresh "sqlplus / as sysdba" connection to the CDB
-- root, so we must switch container + schema again here too.
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = BCCS_PRODUCT;

-- ===================== organization-resource-service =====================

INSERT INTO CHANNEL_TYPE (CHANNEL_TYPE_ID, NAME, STATUS, CODE, CREATE_USER, CREATE_DATETIME)
VALUES (1, 'Chuoi cua hang', '1', 'CHUOI_CH', 'system', SYSDATE);

INSERT INTO CHANNEL_TYPE (CHANNEL_TYPE_ID, NAME, STATUS, CODE, CREATE_USER, CREATE_DATETIME)
VALUES (2, 'Dai ly uy quyen', '1', 'DAI_LY', 'system', SYSDATE);

INSERT INTO CHANNEL_TYPE (CHANNEL_TYPE_ID, NAME, STATUS, CODE, CREATE_USER, CREATE_DATETIME)
VALUES (8, 'Kho chuc nang rieng', '1', 'KHO_CHUC_NANG', 'system', SYSDATE);

INSERT INTO CUST_TYPE (CUST_TYPE, NAME, CREATE_USER, CREATE_DATETIME, STATUS, GROUP_TYPE)
VALUES ('CN', 'Khach hang ca nhan', 'system', SYSDATE, '1', '1');

INSERT INTO CUST_TYPE (CUST_TYPE, NAME, CREATE_USER, CREATE_DATETIME, STATUS, GROUP_TYPE)
VALUES ('DN', 'Khach hang doanh nghiep', 'system', SYSDATE, '1', '2');

INSERT INTO IDENTITY_TYPE (ID_TYPE, NAME, CREATE_USER, CREATE_DATETIME, STATUS, MIN_LENGTH, MAX_LENGTH)
VALUES ('CCCD', 'Can cuoc cong dan', 'system', SYSDATE, '1', 12, 12);

INSERT INTO IDENTITY_TYPE (ID_TYPE, NAME, CREATE_USER, CREATE_DATETIME, STATUS, MIN_LENGTH, MAX_LENGTH)
VALUES ('GPKD', 'Giay phep kinh doanh', 'system', SYSDATE, '1', 10, 15);

INSERT INTO CUST_CHANNEL_TYPE_MAPPING (CUST_CHANNEL_TYPE_MAP_ID, CUST_TYPE, CHANNEL_TYPE_ID, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (1, 'CN', 1, '1', 'system', SYSDATE);

INSERT INTO SHOP (SHOP_ID, NAME, SHOP_CODE, CHANNEL_TYPE_ID, STATUS, PROVINCE, PROVINCE_CODE, ADDRESS, TEL, CREATE_USER, CREATE_DATETIME)
VALUES (100001, 'Cua hang Viettel Cau Giay', 'SHOP001', 1, '1', 'Ha Noi', '01', '123 Cau Giay, Ha Noi', '0243123456', 'system', SYSDATE);

INSERT INTO SHOP (SHOP_ID, NAME, SHOP_CODE, CHANNEL_TYPE_ID, STATUS, PROVINCE, PROVINCE_CODE, ADDRESS, TEL, CREATE_USER, CREATE_DATETIME)
VALUES (100002, 'Cua hang Viettel Ha Dong', 'SHOP002', 2, '1', 'Ha Noi', '01', '45 Ha Dong, Ha Noi', '0243654321', 'system', SYSDATE);

INSERT INTO SHOP (SHOP_ID, NAME, SHOP_CODE, CHANNEL_TYPE_ID, STATUS, PROVINCE, PROVINCE_CODE, ADDRESS, TEL, CREATE_USER, CREATE_DATETIME)
VALUES (100003, 'Kho chuc nang rieng HN01', 'KHO001', 8, '1', 'Ha Noi', '01', 'Kho noi bo, Ha Noi', '0243999999', 'system', SYSDATE);

INSERT INTO STAFF (STAFF_ID, SHOP_ID, STAFF_CODE, NAME, STATUS, TEL, PROVINCE, CREATE_USER, CREATE_DATETIME)
VALUES (200001, 100001, 'NV001', 'Nguyen Van A', '1', '0901234567', 'Ha Noi', 'system', SYSDATE);

INSERT INTO STAFF (STAFF_ID, SHOP_ID, STAFF_CODE, NAME, STATUS, TEL, PROVINCE, CREATE_USER, CREATE_DATETIME)
VALUES (200002, 100002, 'NV002', 'Tran Thi B', '1', '0907654321', 'Ha Noi', 'system', SYSDATE);

INSERT INTO STAFF_EXT (STAFF_EXT_ID, STAFF_ID, KEY, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (300001, 200001, 'BUSINESS_SPEC', 'MOBILE', '1', 'system', SYSDATE);

-- STOCK_CHANNEL_MAPPING mau: du 3 muc phan cap cho cung kho 100003 + kenh 1 (TELECOM_SERVICE_ID=1)
-- Muc kenh: chua gan cua hang/user
INSERT INTO STOCK_CHANNEL_MAPPING (STOCK_CHANNEL_MAPPING_ID, TELECOM_SERVICE_ID, CHANNEL_TYPE_ID, STOCK_SHOP_ID, SHOP_ID, STAFF_ID, EFFECT_DATE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (400001, 1, 1, 100003, NULL, NULL, SYSDATE, '1', 'system', SYSDATE);

-- Muc cua hang: gan them cua hang 100001 (thuoc kenh 1, dung nhu validate "cua hang phai thuoc kenh")
INSERT INTO STOCK_CHANNEL_MAPPING (STOCK_CHANNEL_MAPPING_ID, TELECOM_SERVICE_ID, CHANNEL_TYPE_ID, STOCK_SHOP_ID, SHOP_ID, STAFF_ID, EFFECT_DATE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (400002, 1, 1, 100003, 100001, NULL, SYSDATE, '1', 'system', SYSDATE);

-- Muc user: gan them user 200001 (thuoc cua hang 100001, dung nhu validate "user phai thuoc cua hang")
INSERT INTO STOCK_CHANNEL_MAPPING (STOCK_CHANNEL_MAPPING_ID, TELECOM_SERVICE_ID, CHANNEL_TYPE_ID, STOCK_SHOP_ID, SHOP_ID, STAFF_ID, EFFECT_DATE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (400003, 1, 1, 100003, 100001, 200001, SYSDATE, '1', 'system', SYSDATE);

-- Du lieu test "giat cap" 3 muc cho staff HANTX_DNG_CNKD (250216), shop 270799 (1600080010), channel_type 4 (DL)
-- Kho chuc nang: 200961 (GIUSO_TT), 200280 (TRASAU_CTV), 19808 (KHOSODEP) -- deu co CHANNEL_TYPE_ID=8
-- Muc KENH: channel_type=4, moi shop (-1), moi user (-1)
INSERT INTO STOCK_CHANNEL_MAPPING (STOCK_CHANNEL_MAPPING_ID, TELECOM_SERVICE_ID, CHANNEL_TYPE_ID, STOCK_SHOP_ID, SHOP_ID, STAFF_ID, EFFECT_DATE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (400010, 1, 4, 200961, -1, -1, DATE '2020-01-01', '1', 'system', SYSDATE);
-- Muc CUA HANG: channel_type=4, shop=270799, moi user (-1)
INSERT INTO STOCK_CHANNEL_MAPPING (STOCK_CHANNEL_MAPPING_ID, TELECOM_SERVICE_ID, CHANNEL_TYPE_ID, STOCK_SHOP_ID, SHOP_ID, STAFF_ID, EFFECT_DATE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (400011, 1, 4, 200280, 270799, -1, DATE '2020-01-01', '1', 'system', SYSDATE);
-- Muc USER: channel_type=4, shop=270799, staff=250216
INSERT INTO STOCK_CHANNEL_MAPPING (STOCK_CHANNEL_MAPPING_ID, TELECOM_SERVICE_ID, CHANNEL_TYPE_ID, STOCK_SHOP_ID, SHOP_ID, STAFF_ID, EFFECT_DATE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (400012, 1, 4, 19808, 270799, 250216, DATE '2020-01-01', '1', 'system', SYSDATE);

-- ===================== product-catalog-service =====================

INSERT INTO OPTION_SET (OPTION_SET_ID, CODE, NAME, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (1, 'NATIONALITY', 'Quoc tich', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (1, 1, 'Viet Nam', 'VN', '1', 'system', SYSDATE);

-- Can cho MapActiveInfoService.getUniqueMapActiveInfo (product-policy-service): code nay goi
-- optionSetClient.findByOptionSetCodes(...) roi doc checkMapBusiness.get(0) khong kiem tra rong ->
-- neu thieu option set nay se nem IndexOutOfBoundsException truoc khi chay toi doan tim kiem map active info.
INSERT INTO OPTION_SET (OPTION_SET_ID, CODE, NAME, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (2, 'CHECK_MAP_BUSINESS_PRODUCT', 'Kiem tra map business product', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (2, 2, 'Khong bat buoc', '0', '1', 'system', SYSDATE);

INSERT INTO PRODUCT_SPEC_CHAR (PRODUCT_SPEC_CHAR_ID, NAME, CODE, VALUE_TYPE, CHAR_TYPE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (800001, 'Dung luong data', 'DATA_CAP', 'S', '1', '1', 'system', SYSDATE);

INSERT INTO PRODUCT_PACKAGE (PRODUCT_PACKAGE_ID, NAME, CODE, STATUS, TELECOM_SERVICE_ID, UNIT, CREATE_USER, CREATE_DATETIME)
VALUES (600001, 'Goi cuoc 4G thang', 'PKG001', '1', 1, 'THANG', 'system', SYSDATE);

INSERT INTO PRODUCT_PACKAGE_FEE (PRODUCT_PACKAGE_FEE_ID, PRODUCT_PACKAGE_ID, NAME, PRICE, VAT, STATUS, CODE, CREATE_USER, CREATE_DATETIME)
VALUES (700001, 600001, 'Cuoc thang goi 4G', 100000, 10, '1', 'FEE001', 'system', SYSDATE);

INSERT INTO PRODUCT_OFFERING (PRODUCT_OFFERING_ID, NAME, CODE, TELECOM_SERVICE_ID, STATUS, DESCRIPTION, CREATE_USER, CREATE_DATETIME)
VALUES (500001, 'Goi 4G MIMAX100', 'MIMAX100', 1, '1', 'Goi data 4G toc do cao', 'system', SYSDATE);

INSERT INTO PRODUCT_OFFERING (PRODUCT_OFFERING_ID, NAME, CODE, TELECOM_SERVICE_ID, STATUS, DESCRIPTION, CREATE_USER, CREATE_DATETIME)
VALUES (500002, 'Goi thoai VT200', 'VT200', 1, '1', 'Goi thoai noi mang', 'system', SYSDATE);

-- ===================== product-policy-service =====================

INSERT INTO ACTION (ACTION_CODE, NAME, STATUS, CREATE_USER, CREATE_DATETIME, TYPE, REASON_TYPE)
VALUES ('00', 'Mac dinh', '1', 'system', SYSDATE, '1', 'CONNECT');

-- NOTE: real VSALE action codes like 'VSALE_DAUNOI_DIDONG' (19 chars, see
-- API_VSALE_*.md) do NOT fit ACTION.ACTION_CODE VARCHAR2(10) as declared in
-- ActionEntity (length=10). That's a real mismatch in the entity, not a typo
-- here -- left out of sample data on purpose. Confirmed via ORA-12899 on first
-- container init.

INSERT INTO REASON (REASON_ID, REASON_CODE, REASON_TYPE, NAME, PAY_TYPE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (1, 'HN001', 'CONNECT', 'Hoa mang thue bao tra truoc', '2', '1', 'system', SYSTIMESTAMP);

INSERT INTO REASON (REASON_ID, REASON_CODE, REASON_TYPE, NAME, PAY_TYPE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (2, 'HN002', 'CONNECT', 'Hoa mang thue bao tra sau', '1', '1', 'system', SYSTIMESTAMP);

INSERT INTO DISCOUNT_PROMOTION (DISCOUNT_PROMOTION_ID, TELECOM_SERVICE_ID, CODE, NAME, STATUS, EFFECT_DATETIME, CREATE_USER, CREATE_DATETIME)
VALUES (900001, '1', 'KM001', 'Khuyen mai data thang dau', '1', SYSTIMESTAMP, 'system', SYSTIMESTAMP);

INSERT INTO DISCOUNT_PROMOTION_CHAR_USE (DISCOUNT_PROMOTION_CHAR_USE_ID, DISCOUNT_PROMOTION_ID, PRODUCT_SPEC_CHAR_ID, STATUS, SPECIFIC_VALUE, CREATE_USER, CREATE_DATETIME)
VALUES (900101, 900001, 800001, '1', '5GB', 'system', SYSTIMESTAMP);

-- EFFECT_DATE la bat buoc phai co gia tri va o qua khu de qua duoc bo loc "active window"
-- trong MapActiveInfoRepositoryCustomImpl.buildQuery (STATUS != 0 AND sysdate > trunc(EFFECT_DATE)
-- AND (END_DATE is null or END_DATE >= trunc(sysdate))) -- thieu EFFECT_DATE se khien moi truy van
-- findByExample (ca DB va Elasticsearch) tra ve rong du STATUS/cac truong khac dung.
INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, STATUS, SHOP_CODE, ACTION_CODE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000001, 1, 'MIMAX100', 1, 'ALL', 1, 'ALL', 1, 'ALL', '00', 'system', SYSDATE, DATE '2020-01-01');

-- 20 ban ghi mau bo sung (2026-07-28) de test/debug luong Elasticsearch cache cua findByExampleForProduct.
-- Da dang hoa productCode/actionCode/provinceCode/channelTypeId/regReasonId/telServiceId/promCode.
INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000010, 1, 'MIMAX100', 'Goi 4G MIMAX100', 1, 'ALL', 1, 'ALL', 'ALL', 'ALL', 1, 'SHOP001', 'ALL', '00', 'ALL', 'CN', 'ALL', 'ALL', '4G', '2', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000011, 1, 'MIMAX150', 'Goi 4G MIMAX150', 1, 'ALL', 1, 'ALL', 'ALL', 'ALL', 1, 'ALL', 'ALL', '00', 'ALL', 'DN', 'ALL', 'ALL', '4G', '1', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000012, 1, 'VT200', 'Goi thoai VT200', 1, 'ALL', 2, '01', 'ALL', 'ALL', 1, 'SHOP002', 'NV002', '00', 'ALL', 'CN', 'ALL', 'ALL', 'ALL', '2', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000013, 1, 'VT200', 'Goi thoai VT200', 2, 'ALL', 1, '01', '01001', 'ALL', 1, 'ALL', 'ALL', '01', 'ALL', 'CN', 'ALL', 'ALL', 'ALL', '2', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000014, 1, 'DATA4G50', 'Goi Data 4G 50GB', 1, 'KM001', 1, 'ALL', 'ALL', 'ALL', 1, 'ALL', 'ALL', '00', 'ALL', 'ALL', 'ALL', 'ALL', '4G', '2', 'system', SYSDATE, DATE '2020-01-01');

-- PAY_TYPE la VARCHAR2(1) nen khong the dung sentinel 'ALL'/'-1' (qua dai) -- de NULL (buildColumnCondition co nhanh "OR column IS NULL" nen van khop moi payType khi tim kiem).
INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000015, 1, 'DATA4G50', 'Goi Data 4G 50GB', 1, 'ALL', 2, '79', 'ALL', 'ALL', 1, 'ALL', 'ALL', '02', 'ALL', 'ALL', 'ALL', 'ALL', '4G', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000016, 2, 'HOME50', 'Goi Internet Home 50Mbps', 1, 'ALL', 1, 'ALL', 'ALL', 'ALL', 1, 'ALL', 'ALL', '00', 'ALL', 'ALL', 'ALL', 'ALL', 'FTTH', '1', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000017, 2, 'HOME100', 'Goi Internet Home 100Mbps', 2, 'ALL', 1, '48', 'ALL', 'ALL', 1, 'ALL', 'ALL', '00', 'ALL', 'ALL', 'ALL', 'ALL', 'FTTH', '1', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000018, 1, 'MIMAX200', 'Goi 4G MIMAX200', 1, 'ALL', 1, 'ALL', 'ALL', 'ALL', 1, 'SHOP001', 'NV001', '00', 'HSSV', 'CN', 'ALL', 'ALL', '4G', '2', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000019, 1, 'MIMAX200', 'Goi 4G MIMAX200', 1, 'KM001', 2, 'ALL', 'ALL', 'ALL', 1, 'ALL', 'ALL', '01', 'ALL', 'ALL', 'ALL', 'ALL', '4G', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000020, 1, 'VT500', 'Goi thoai VT500', 1, 'ALL', 1, 'ALL', 'ALL', 'ALL', 1, 'ALL', 'ALL', '00', 'ALL', 'ALL', 'ALL', 'ALL', 'ALL', '2', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000021, 1, 'VT500', 'Goi thoai VT500', 2, 'ALL', 1, '01', 'ALL', 'ALL', 1, 'SHOP001', 'ALL', '01', 'ALL', 'ALL', 'ALL', 'ALL', 'ALL', '1', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000022, 1, 'DATA4G100', 'Goi Data 4G 100GB', 1, 'ALL', 1, 'ALL', 'ALL', 'ALL', 1, 'ALL', 'ALL', '00', 'ALL', 'DN', 'ALL', 'ALL', '4G', '2', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000023, 1, 'DATA4G100', 'Goi Data 4G 100GB', 1, 'ALL', 2, '01', 'ALL', 'ALL', 0, 'ALL', 'ALL', '00', 'ALL', 'ALL', 'ALL', 'ALL', '4G', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000024, 1, 'MIMAX300', 'Goi 4G MIMAX300', 1, 'ALL', 1, 'ALL', 'ALL', 'ALL', 1, 'ALL', 'ALL', '00', 'ALL', 'ALL', 'ALL', 'ALL', '5G', '2', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000025, 1, 'MIMAX300', 'Goi 4G MIMAX300', 2, 'KM001', 1, 'ALL', 'ALL', 'ALL', 1, 'ALL', 'ALL', '01', 'ALL', 'ALL', 'ALL', 'ALL', '5G', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000026, 19, 'CABLETV50', 'Goi truyen hinh cap 50 kenh', 1, 'ALL', 1, 'ALL', 'ALL', 'ALL', 1, 'ALL', 'ALL', '00', 'ALL', 'ALL', 'ALL', 'ALL', 'ALL', '1', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000027, 25, 'INTERNETEOC50', 'Goi Internet EoC 50Mbps', 1, 'ALL', 1, 'ALL', 'ALL', 'ALL', 1, 'ALL', 'ALL', '00', 'ALL', 'ALL', 'ALL', 'ALL', 'ALL', '1', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, PAY_TYPE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000028, 1, 'MIMAX100', 'Goi 4G MIMAX100', 1, 'ALL', 1, '01', '01001', 'ALL', 0, 'ALL', 'ALL', '00', 'ALL', 'ALL', 'ALL', 'ALL', '4G', '2', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO (ID, TEL_SERVICE_ID, PRODUCT_CODE, PRODUCT_NAME, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, DISTRICT_CODE, PRECINCT_CODE, STATUS, SHOP_CODE, STAFF_CODE, ACTION_CODE, CUSTOMER_GROUP, CUSTOMER_TYPE, SUB_TYPE, SUB_GROUP, TECHNOLOGY, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000029, 1, 'MIMAX150', 'Goi 4G MIMAX150', 3, 'ALL', 1, 'ALL', 'ALL', 'ALL', 1, 'ALL', 'ALL', '00', 'ALL', 'ALL', 'ALL', 'ALL', '4G', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAP_ACTIVE_INFO_TGDD (ID, TEL_SERVICE_ID, PRODUCT_CODE, REG_REASON_ID, PROM_CODE, CHANNEL_TYPE_ID, PROVINCE_CODE, STATUS, SHOP_CODE, ACTION_CODE, CREATE_USER, ISSUE_DATETIME, EFFECT_DATE)
VALUES (1000002, 1, 'MIMAX100', 1, 'ALL', 1, 'ALL', 1, 'ALL', '00', 'system', SYSDATE, DATE '2020-01-01');

INSERT INTO MAPPING (ID, VAS, PRODUCT_NAME, PRODUCT_CODE, ACTION_CODE, REASON_ID, TEL_SERVICE_ID, STATUS, USER_CREATE, CREATE_DATETIME)
VALUES (1100001, 'MIMAX100', 'Goi 4G MIMAX100', 'MIMAX100', '00', 1, 1, '1', 'system', SYSDATE);

INSERT INTO REF_PRODUCT_PACKAGE (PRODUCT_PACKAGE_ID, NAME, CODE, STATUS, TELECOM_SERVICE_ID)
VALUES (600001, 'Goi cuoc 4G thang', 'PKG001', '1', 1);

INSERT INTO REF_PRODUCT_PACKAGE_FEE (PRODUCT_PACKAGE_FEE_ID, PRODUCT_PACKAGE_ID, PRICE_POLICY_ID, PRICE_TYPE_ID, NAME, PRICE, STATUS)
VALUES (700001, 600001, 1, 1, 'Cuoc thang goi 4G', 100000, '1');

INSERT INTO REF_PROD_PACK_PO_TYPE (PROD_PACK_TYPE_ID, PRODUCT_PACKAGE_ID, PRODUCT_OFFER_TYPE_ID, STATUS)
VALUES (1, 600001, 1, '1');

-- ===================== product-area-service =====================

INSERT INTO AREA (AREA_CODE, PROVINCE, NAME, FULL_NAME, PROVINCE_CODE, STATUS, CENTER, CREATE_USER, CREATE_DATETIME)
VALUES ('01', '01', 'Ha Noi', 'Thanh pho Ha Noi', '01', '1', '1', 'system', SYSTIMESTAMP);

INSERT INTO AREA (AREA_CODE, PARENT_CODE, PROVINCE, DISTRICT, NAME, FULL_NAME, PROVINCE_CODE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES ('01001', '01', '01', '001', 'Cau Giay', 'Quan Cau Giay', '01', '1', 'system', SYSTIMESTAMP);

COMMIT;
