-- Cau hinh nhom VAS loai tru lan nhau cho ProductOfferingService.getListVas (product-catalog-service).
-- Thay the file vascode_config.properties cua he thong monolith cu: 1 OPTION_SET.CODE duy nhat
-- ('VAS_EXCLUSIVE_GROUP'), moi dong OPTION_SET_VALUE la 1 ma VAS (VALUE) thuoc 1 nhom (NAME).
-- VAS cung NAME trong nhom nay la loai tru lan nhau (chi duoc chon toi da 1 trong cung 1 don hang).
--
-- Da doi chieu tung dong voi ham getVasExclude() cua code cu (khong doan theo ten bien Java, vi bien
-- "PRE_IPP" trong code cu thuc ra doc du lieu tu property key "POS_IPP_*" - da xac nhan va dat ten
-- nhom dung theo du lieu that la POS_IPP).
--
-- Rieng PRE_BB/POS_BB co the trung ma VAS (vi du BBMAIL, BBCHT xuat hien o ca 2 nhom trong file cu) -
-- code phan biet dua theo SUB_TYPE cua tung ban ghi VAS luc runtime (PRE='2', POST='1', xem
-- Const.SUB_TYPE trong product-catalog-service).
--
-- Each *.sql init script gets its own fresh "sqlplus / as sysdba" connection to the CDB root,
-- so we must switch container + schema again here too.
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = BCCS_PRODUCT;

INSERT INTO OPTION_SET (OPTION_SET_ID, CODE, NAME, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (3, 'VAS_EXCLUSIVE_GROUP', 'Nhom VAS loai tru lan nhau', '1', 'system', SYSDATE);

-- ===== PRE_GPRS (23 ma, GPRS tra truoc) =====
INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (3, 3, 'PRE_GPRS', 'GPRS0', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (4, 3, 'PRE_GPRS', 'GPRS5', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (5, 3, 'PRE_GPRS', 'GPRS10', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (6, 3, 'PRE_GPRS', 'GPRS15', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (7, 3, 'PRE_GPRS', 'GPRS25', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (8, 3, 'PRE_GPRS', 'GPRS50', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (9, 3, 'PRE_GPRS', 'MBI1xx', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (10, 3, 'PRE_GPRS', 'MBI2xx', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (11, 3, 'PRE_GPRS', 'MBI3xx', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (12, 3, 'PRE_GPRS', 'MBI4xx', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (13, 3, 'PRE_GPRS', 'D3U300', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (14, 3, 'PRE_GPRS', 'D3U012', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (15, 3, 'PRE_GPRS', 'D3U100', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (16, 3, 'PRE_GPRS', 'MI200x', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (17, 3, 'PRE_GPRS', 'MI25xx', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (18, 3, 'PRE_GPRS', 'MI80xx', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (19, 3, 'PRE_GPRS', 'D300', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (20, 3, 'PRE_GPRS', 'MIMIN', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (21, 3, 'PRE_GPRS', 'MI10', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (22, 3, 'PRE_GPRS', 'MI30', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (23, 3, 'PRE_GPRS', 'MIMAX', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (24, 3, 'PRE_GPRS', 'DMAX', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (25, 3, 'PRE_GPRS', 'DMAX200', '1', 'system', SYSDATE);

-- ===== PRE_G1 (2 ma) =====
INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (26, 3, 'PRE_G1', 'G1FRPR', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (27, 3, 'PRE_G1', 'G1xxxx', '1', 'system', SYSDATE);

-- ===== POS_GPRS (37 ma, GPRS tra sau) =====
INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (28, 3, 'POS_GPRS', 'GPR_D0', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (29, 3, 'POS_GPRS', 'GPR_D5', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (30, 3, 'POS_GPRS', 'GP_D10', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (31, 3, 'POS_GPRS', 'GP_D15', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (32, 3, 'POS_GPRS', 'GP_D25', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (33, 3, 'POS_GPRS', 'GP_D50', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (34, 3, 'POS_GPRS', 'G_D300', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (35, 3, 'POS_GPRS', 'G_BIS1', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (36, 3, 'POS_GPRS', 'G_BES2', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (37, 3, 'POS_GPRS', 'G_BIS2', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (38, 3, 'POS_GPRS', 'GP_BES', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (39, 3, 'POS_GPRS', 'G_BIS3', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (40, 3, 'POS_GPRS', 'G_BIS4', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (41, 3, 'POS_GPRS', 'G_BES3', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (42, 3, 'POS_GPRS', 'DMOB00', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (43, 3, 'POS_GPRS', 'DMOB10', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (44, 3, 'POS_GPRS', 'DMOB25', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (45, 3, 'POS_GPRS', 'DMOB50', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (46, 3, 'POS_GPRS', 'DMU015', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (47, 3, 'POS_GPRS', 'DMU400', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (48, 3, 'POS_GPRS', 'DMU100', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (49, 3, 'POS_GPRS', 'DMBIS1', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (50, 3, 'POS_GPRS', 'DMBIS2', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (51, 3, 'POS_GPRS', 'DMBIS3', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (52, 3, 'POS_GPRS', 'DMBIS4', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (53, 3, 'POS_GPRS', 'DMBESS', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (54, 3, 'POS_GPRS', 'DMBES2', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (55, 3, 'POS_GPRS', 'DMBES3', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (56, 3, 'POS_GPRS', 'MI0007', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (57, 3, 'POS_GPRS', 'MI0006', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (58, 3, 'POS_GPRS', 'MI0003', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (59, 3, 'POS_GPRS', 'MIMINX', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (60, 3, 'POS_GPRS', 'MI10XX', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (61, 3, 'POS_GPRS', 'MI30XX', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (62, 3, 'POS_GPRS', 'MIMAXX', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (63, 3, 'POS_GPRS', 'DMAXXX', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (64, 3, 'POS_GPRS', 'DMAX200X', '1', 'system', SYSDATE);

-- ===== POS_G1 (2 ma) =====
INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (65, 3, 'POS_G1', 'POSTG1', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (66, 3, 'POS_G1', 'G1FRPO', '1', 'system', SYSDATE);

-- ===== POS_AP_BH (6 ma) =====
INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (67, 3, 'POS_AP_BH', 'BH_P1', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (68, 3, 'POS_AP_BH', 'BH_P2', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (69, 3, 'POS_AP_BH', 'BHP_MP', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (70, 3, 'POS_AP_BH', 'BH_A1', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (71, 3, 'POS_AP_BH', 'BH_A2', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (72, 3, 'POS_AP_BH', 'BHA_MP', '1', 'system', SYSDATE);

-- ===== PRE_BB (4 ma) / POS_BB (5 ma) - luu y BBMAIL/BBCHT trung ma o ca 2 nhom, =====
-- ===== phan biet dua theo SUB_TYPE cua tung ban ghi VAS luc runtime =====
INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (73, 3, 'PRE_BB', 'BBMAIL', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (74, 3, 'PRE_BB', 'BBCHT', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (75, 3, 'PRE_BB', 'BBMAIL7', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (76, 3, 'PRE_BB', 'BBCHT7', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (77, 3, 'POS_BB', 'BBMAIL', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (78, 3, 'POS_BB', 'BBCHT', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (79, 3, 'POS_BB', 'BBWEB', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (80, 3, 'POS_BB', 'BBECO', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (81, 3, 'POS_BB', 'BBENTER', '1', 'system', SYSDATE);

-- ===== POS_IPP (4 ma) - luu y: bien Java ten "PRE_IPP" trong code cu nhung thuc te doc =====
-- ===== du lieu tu property key "POS_IPP_*", da xac nhan va dat dung ten nhom la POS_IPP =====
INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (82, 3, 'POS_IPP', 'TBCGKDT', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (83, 3, 'POS_IPP', 'TBVN', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (84, 3, 'POS_IPP', 'BTTD', '1', 'system', SYSDATE);

INSERT INTO OPTION_SET_VALUE (OPTION_SET_VALUE_ID, OPTION_SET_ID, NAME, VALUE, STATUS, CREATE_USER, CREATE_DATETIME)
VALUES (85, 3, 'POS_IPP', 'CCGTT', '1', 'system', SYSDATE);
