-- ============================================================================
-- Baseline schema cho 1 instance Gateway Manager MOI (vd 1 doi BCCS tu trien
-- khai rieng) - CHI gom 8 bang + 1 index, KHONG gom du lieu demo/seed (moi doi
-- tu tao Upstream Service/Endpoint cua rieng minh qua UI sau khi len).
--
-- Nguon: trich nguyen DDL da xac nhan chay that (khong loi cu phap) tu
-- ddl-gateway-manager.sql/gateway-manager-production-setup.sql (DBMS_METADATA.GET_DDL
-- tren Oracle dev that + cac ALTER TABLE lich su "lan 1..9", da gop het thanh 1
-- schema hoan chinh tinh den 2026-09-03). KHONG dung kieu BOOLEAN/JSON (chi co tu
-- Oracle 23c) - NUMBER(1,0)+CHECK thay the - de tuong thich Oracle 19c.
--
-- Instance DA CO san du lieu (vd db-local dev hien tai, schema da khop dung noi
-- dung file nay): Flyway se tu BASELINE (danh dau "da o V1", KHONG chay lai file
-- nay) nho spring.flyway.baseline-on-migrate=true + baseline-version=1 (xem
-- application.yml) - khong can thao tac tay, khong dung toi du lieu san co.
-- ============================================================================

CREATE TABLE "UPSTREAM_SERVICE"
   (	"ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"BASE_HOST" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CIRCUIT_BREAKER_ENABLED" NUMBER(1,0) NOT NULL ENABLE,
	"CONNECT_TIMEOUT_MS" NUMBER(10,0) NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE,
	"DESCRIPTION" VARCHAR2(255 CHAR),
	"FAILURE_RATE_THRESHOLD" NUMBER(10,0) NOT NULL ENABLE,
	"MAX_CONCURRENT_CALLS" NUMBER(10,0) DEFAULT 20 NOT NULL ENABLE,
	"MAX_WAIT_DURATION_MS" NUMBER(10,0) DEFAULT 500 NOT NULL ENABLE,
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"READ_TIMEOUT_MS" NUMBER(10,0) NOT NULL ENABLE,
	"RETRY_ENABLED" NUMBER(1,0) NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE,
	 CHECK (circuit_breaker_enabled in (0,1)) ENABLE,
	 CHECK (retry_enabled in (0,1)) ENABLE,
	 CONSTRAINT "UPSTREAM_SERVICE_PK" PRIMARY KEY ("ID") ENABLE,
	 CONSTRAINT "UKR9K2UNQ519ISGPHWC5EMCHYUC" UNIQUE ("NAME") ENABLE
   );

CREATE TABLE "ENDPOINT_CONFIG"
   (	"ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (6) WITH TIME ZONE,
	"DESCRIPTION" VARCHAR2(255 CHAR),
	"METHOD" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"OUTPUT_ENCODING" VARCHAR2(255 CHAR),
	"PATH" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"IS_SEQUENTIAL" NUMBER(1,0) NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) WITH TIME ZONE,
	"IDEMPOTENCY_ENABLED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"IDEMPOTENCY_TTL_SECONDS" NUMBER(10,0) DEFAULT 86400 NOT NULL ENABLE,
	"PARALLEL_EXECUTION" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"RESPONSE_CACHE_ENABLED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"RESPONSE_CACHE_TTL_SECONDS" NUMBER(10,0) DEFAULT 300 NOT NULL ENABLE,
	 CHECK (method in ('GET','POST','PUT','DELETE','PATCH')) ENABLE,
	 CHECK (is_sequential in (0,1)) ENABLE,
	 CHECK (idempotency_enabled in (0,1)) ENABLE,
	 CHECK (parallel_execution in (0,1)) ENABLE,
	 CHECK (response_cache_enabled in (0,1)) ENABLE,
	 CONSTRAINT "ENDPOINT_CONFIG_PK" PRIMARY KEY ("ID") ENABLE,
	 CONSTRAINT "UK5SBR9SP37R2WRGTA6BTBEE3XB" UNIQUE ("PATH") ENABLE
   );

CREATE TABLE "BACKEND_STEP"
   (	"ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"FORWARD_ORIGINAL_BODY" NUMBER(1,0) NOT NULL ENABLE,
	"GROUP_NAME" VARCHAR2(255 CHAR),
	"METHOD" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"STEP_ORDER" NUMBER(10,0) NOT NULL ENABLE,
	"TARGET_FIELD" VARCHAR2(255 CHAR),
	"URL_PATTERN" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"ENDPOINT_ID" VARCHAR2(255 CHAR),
	"UPSTREAM_SERVICE_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	-- NUMBER(1,0)+CHECK (khong dung BOOLEAN - kieu do CHI co tu Oracle 23c tro
	-- len, dung lam kieu cot bang tren 19c se loi ORA-00902).
	"CACHE_ENABLED" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE,
	"CACHE_TTL_SECONDS" NUMBER(10,0) DEFAULT 300 NOT NULL ENABLE,
	"CANVAS_X" NUMBER(10,0),
	"CANVAS_Y" NUMBER(10,0),
	"CONDITION_EXPECTED_VALUE" VARCHAR2(255 CHAR),
	"CONDITION_OPERATOR" VARCHAR2(255 CHAR),
	"CONDITION_SOURCE_FIELD" VARCHAR2(255 CHAR),
	"CONDITION_SOURCE_STEP_ORDER" NUMBER(10,0),
	"CONDITION_SOURCE_TYPE" VARCHAR2(255 CHAR),
	"NEXT_STEP_ORDER_IF_FALSE" NUMBER(10,0),
	"NEXT_STEP_ORDER_IF_TRUE" NUMBER(10,0),
	"CONNECT_TIMEOUT_MS" NUMBER(10,0),
	"READ_TIMEOUT_MS" NUMBER(10,0),
	"ON_ERROR_STEP_ORDER" NUMBER(10,0),
	"PARALLEL_GROUP" NUMBER(10,0),
	"COMPENSATION_UPSTREAM_SERVICE_ID" VARCHAR2(255 CHAR),
	"COMPENSATION_METHOD" VARCHAR2(255 CHAR),
	"COMPENSATION_URL_PATTERN" VARCHAR2(255 CHAR),
	 CHECK (forward_original_body in (0,1)) ENABLE,
	 CHECK (cache_enabled in (0,1)) ENABLE,
	 CHECK (method in ('GET','POST','PUT','DELETE','PATCH')) ENABLE,
	 CHECK ((condition_operator in ('EQUALS','NOT_EQUALS','EXISTS','NOT_EXISTS','GREATER_THAN','GREATER_THAN_OR_EQUAL','LESS_THAN','LESS_THAN_OR_EQUAL'))) ENABLE,
	 CHECK ((condition_source_type in ('STEP_RESPONSE','REQUEST_BODY','STEP_RESPONSE_ARRAY_AGGREGATE'))) ENABLE,
	 CHECK (compensation_method in ('GET','POST','PUT','DELETE','PATCH')) ENABLE,
	 CONSTRAINT "BACKEND_STEP_PK" PRIMARY KEY ("ID") ENABLE,
	 CONSTRAINT "FKRTN26VYRBRFLYH5FA838XWTL2" FOREIGN KEY ("ENDPOINT_ID")
	  REFERENCES "ENDPOINT_CONFIG" ("ID") ENABLE,
	 CONSTRAINT "FK2RCXPBA4YOIDGMRN8I0S3OFTT" FOREIGN KEY ("UPSTREAM_SERVICE_ID")
	  REFERENCES "UPSTREAM_SERVICE" ("ID") ENABLE,
	 CONSTRAINT "BACKEND_STEP_COMP_UPSTREAM_FK" FOREIGN KEY ("COMPENSATION_UPSTREAM_SERVICE_ID")
	  REFERENCES "UPSTREAM_SERVICE" ("ID") ENABLE
   );

CREATE TABLE "BACKEND_STEP_ALLOW"
   (	"STEP_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"FIELD_NAME" VARCHAR2(255 CHAR),
	 CONSTRAINT "FKLJYTFUDPJNU325RXYAG45C0DT" FOREIGN KEY ("STEP_ID")
	  REFERENCES "BACKEND_STEP" ("ID") ENABLE
   );

CREATE TABLE "BACKEND_STEP_DENY"
   (	"STEP_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"FIELD_NAME" VARCHAR2(255 CHAR),
	 CONSTRAINT "FKQXQIJEVJM7G8Y9BQOXSQ57NHF" FOREIGN KEY ("STEP_ID")
	  REFERENCES "BACKEND_STEP" ("ID") ENABLE
   );

CREATE TABLE "BACKEND_STEP_MAPPING"
   (	"STEP_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"TARGET_FIELD" VARCHAR2(255 CHAR),
	"SOURCE_FIELD" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	 CONSTRAINT "BACKEND_STEP_MAPPING_PK" PRIMARY KEY ("STEP_ID", "SOURCE_FIELD") ENABLE,
	 CONSTRAINT "FKT06QSCVM4OA358VRUBIG5ACMD" FOREIGN KEY ("STEP_ID")
	  REFERENCES "BACKEND_STEP" ("ID") ENABLE
   );

CREATE TABLE "FIELD_MAPPING"
   (	"ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"SOURCE_ARRAY_FIELD" VARCHAR2(255 CHAR),
	"SOURCE_ELEMENT_FIELD" VARCHAR2(255 CHAR),
	"SOURCE_FIELD" VARCHAR2(255 CHAR),
	"SOURCE_STEP_ORDER" NUMBER(10,0),
	"SOURCE_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CONSTANT_VALUE" VARCHAR2(4000 CHAR),
	"TARGET_PARAM_NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"TARGET_STEP_ORDER" NUMBER(10,0) NOT NULL ENABLE,
	"TARGET_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"ENDPOINT_ID" VARCHAR2(255 CHAR),
	"MAPPING_ORDER" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
	"TARGET_CONTEXT" VARCHAR2(255 CHAR) DEFAULT 'MAIN' NOT NULL ENABLE,
	 CONSTRAINT "FIELD_MAPPING_SOURCE_TYPE_CHK" CHECK (source_type in ('STEP_RESPONSE','REQUEST_BODY','QUERY_PARAM','STEP_RESPONSE_ARRAY_AGGREGATE','CONSTANT','STEP_RESPONSE_ARRAY_MERGE')) ENABLE,
	 CHECK (target_type in ('PATH','QUERY','HEADER','BODY_FIELD')) ENABLE,
	 CONSTRAINT "FIELD_MAPPING_TARGET_CONTEXT_CHK" CHECK (target_context in ('MAIN','COMPENSATION')) ENABLE,
	 CONSTRAINT "FIELD_MAPPING_PK" PRIMARY KEY ("ID") ENABLE,
	 CONSTRAINT "FKG9BDKEU7BU7USNQSCONIOKV8K" FOREIGN KEY ("ENDPOINT_ID")
	  REFERENCES "ENDPOINT_CONFIG" ("ID") ENABLE
   );

CREATE TABLE "ENDPOINT_CONFIG_VERSION"
   (	"ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CHANGE_TYPE" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"CREATED_AT" TIMESTAMP (9) WITH TIME ZONE,
	"ENDPOINT_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"METHOD" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"NAME" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"PATH" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"SNAPSHOT_JSON" CLOB NOT NULL ENABLE,
	"VERSION_NUMBER" NUMBER(10,0) NOT NULL ENABLE,
	 CHECK ((change_type in ('CREATED','UPDATED','ROLLED_BACK'))) ENABLE,
	 CHECK ((method in ('GET','POST','PUT','DELETE','PATCH'))) ENABLE,
	 CONSTRAINT "ENDPOINT_CONFIG_VERSION_PK" PRIMARY KEY ("ID") ENABLE,
	 CONSTRAINT "UK2NPOJ2PDGV4HFROGTJSFCPQXU" UNIQUE ("ENDPOINT_ID", "VERSION_NUMBER") ENABLE
   );

CREATE INDEX "IDX_ECV_ENDPOINT_ID" ON "ENDPOINT_CONFIG_VERSION" ("ENDPOINT_ID");
