<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.viettel.bccs</groupId>
        <artifactId>bccs-build-parent</artifactId>
        <version>0.1.14-SNAPSHOT</version>
        <relativePath/>
    </parent>

    <artifactId>product-policy-service</artifactId>
    <packaging>jar</packaging>

    <properties>
        <springdoc-openapi.version>3.0.3</springdoc-openapi.version>
    </properties>


    <name>product-policy-service</name>
    <description>Product policy service</description>

    <dependencies>
        <dependency>
            <groupId>com.viettel.bccs</groupId>
            <artifactId>bccs-starter-service-base</artifactId>
        </dependency>
        <dependency>
            <groupId>com.viettel.bccs</groupId>
            <artifactId>bccs-starter-data</artifactId>
        </dependency>
        <dependency>
            <groupId>com.viettel.bccs</groupId>
            <artifactId>bccs-starter-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>com.viettel.bccs</groupId>
            <artifactId>bccs-starter-cache</artifactId>
        </dependency>
        <dependency>
            <groupId>com.viettel.bccs</groupId>
            <artifactId>bccs-starter-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>co.elastic.clients</groupId>
            <artifactId>elasticsearch-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch.client</groupId>
            <artifactId>elasticsearch-rest-client</artifactId>
        </dependency>
        <dependency>
            <groupId>com.viettel.bccs</groupId>
            <artifactId>bccs-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit5</artifactId>
            <version>1.4.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>${springdoc-openapi.version}</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>product-policy-service</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
